export const headers = {
  BlobsInfo: 'x-nf-blobs-info',
  DeployID: 'x-nf-deploy-id',
  DeployContext: 'x-nf-deploy-context',
  FeatureFlags: 'x-nf-feature-flags',
  ForwardedHost: 'x-forwarded-host',
  ForwardedProtocol: 'x-forwarded-proto',
  Functions: 'x-nf-edge-functions',
  InvocationMetadata: 'x-nf-edge-functions-metadata',
  Geo: 'x-nf-geo',
  Passthrough: 'x-nf-passthrough',
  PassthroughHost: 'x-nf-passthrough-host',
  PassthroughProtocol: 'x-nf-passthrough-proto',
  IP: 'x-nf-client-connection-ip',
  Site: 'X-NF-Site-Info',
  DebugLogging: 'x-nf-debug-logging',
  Account: 'x-nf-account-info',
  RequestID: 'x-nf-request-id',
  AvailableFunctions: 'x-nf-available-edge-functions',
  FunctionDeclarations: 'x-nf-edge-functions-declarations',
  UncaughtError: 'x-nf-uncaught-error',

  AcceptEncoding: 'accept-encoding',
}
